name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read Configuration
        run: docker-compose -f docker-compose.yml config
      - name: Build the stack
        run: docker-compose up -d
      - name: Test Traefik exposes HTTP
        run: docker run --network container:traefik appropriate/curl -s --retry 10 --retry-connrefused http://localhost
      - name: Test Traefik exposes HTTPS
        run: docker run --network container:traefik appropriate/curl -s --retry 10 --retry-connrefused https://localhost --insecure
      - name: Test Traefik Forward Auth Access
        run: docker run --network container:traefik appropriate/curl -s --retry 10 --retry-connrefused http://traefikforward:4181
      - name: Test Elasticsearch Access
        run: docker run --network container:traefik appropriate/curl -s --retry 10 --retry-connrefused http://elasticsearch:9200