name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Test HTTP
        run: docker run appropriate/curl -s --retry 10 --retry-connrefused http://localhost
      - name: Test HTTPS
        run: docker run appropriate/curl -s --retry 10 --retry-connrefused https://localhost